
# POST http://localhost:8080/healthy HTTP/1.1
# content-type: application/json

# {
#     "title": "Log In!!!",
#     "message": "Remember to sign in"
# }

###
GET http://localhost:8080/healthy

###
GET http://localhost:8080/hirigana
